//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccessGateway.Automation.DAGUnitTest
{
	using System;
	using System.Data;
	using System.Linq;
	using System.Collections.Generic;
	using Framework.DataAccessGateway.Core;
	
	
	public partial interface IDAGUnitTest
	{
		
		IData_Repository Data
		{
			get;
		}
		
		ISubTable_Repository SubTable
		{
			get;
		}
	}
	
	public partial class DAGUnitTest : IDAGUnitTest
	{
		
		private Framework.DataAccessGateway.Core.IDBHandler _DBHandler { get; }
		
		public IData_Repository Data { get; private set; }
		
		public ISubTable_Repository SubTable { get; private set; }
		
		public DAGUnitTest(Framework.DataAccessGateway.Core.IDBHandler dbHandler)
		{
			_DBHandler = dbHandler;
			Data = new Data_Repository(_DBHandler);
			SubTable = new SubTable_Repository(_DBHandler);
			Initialize();
		}
		
		public DAGUnitTest(string connectionString)
		{
			_DBHandler = new DBHandler(connectionString, DBHandlerType.DbHandlerMSSQL);
			Data = new Data_Repository(_DBHandler);
			SubTable = new SubTable_Repository(_DBHandler);
			Initialize();
		}
		
		partial void Initialize();
	}
}

