//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccessGateway.Automation.DAGUnitTest
{
	using System;
	using System.Data;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using Framework.DataAccessGateway.Core;
	
	
	public class sysdiagrams_Key
	{
		
		[Required()]
		[DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.Int, System.Data.ParameterDirection.ReturnValue)]
		public int diagram_id { get; set; }
	}
	
	public class sysdiagrams
	{
		
		[Required()]
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.NVarChar, System.Data.ParameterDirection.Input)]
		public string name { get; set; }
		
		[Required()]
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.Int, System.Data.ParameterDirection.Input)]
		public int principal_id { get; set; }
		
		[Required()]
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.Int, System.Data.ParameterDirection.ReturnValue)]
		public int diagram_id { get; set; }
		
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.Int, System.Data.ParameterDirection.Input)]
		public System.Nullable<int> version { get; set; }
		
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.VarBinary, System.Data.ParameterDirection.Input)]
		public byte[] definition { get; set; }
	}
	
	public class sysdiagrams_Ext
	{
		
		[Required()]
		[DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.Int, System.Data.ParameterDirection.ReturnValue)]
		public int _diagram_id { get; set; }
		
		[Required()]
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.NVarChar, System.Data.ParameterDirection.Input)]
		public string name { get; set; }
		
		[Required()]
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.Int, System.Data.ParameterDirection.Input)]
		public int principal_id { get; set; }
		
		[Required()]
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.Int, System.Data.ParameterDirection.ReturnValue)]
		public int diagram_id { get; set; }
		
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.Int, System.Data.ParameterDirection.Input)]
		public System.Nullable<int> version { get; set; }
		
		[DBHandlerProperty(Framework.DataAccessGateway.Core.DBHandlerDataType.VarBinary, System.Data.ParameterDirection.Input)]
		public byte[] definition { get; set; }
	}
}

