//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccessGateway.Automation.DAGUnitTest
{
	using System;
	using System.Data;
	using System.Linq;
	using System.Collections.Generic;
	using Framework.DataAccessGateway.Core;
	
	
	public partial class DAGUnitTest
	{
		
		public Data_Repository Data { get; private set; }
		
		public SubTable_Repository SubTable { get; private set; }
		
		public sysdiagrams_Repository sysdiagrams { get; private set; }
		
		public DAGUnitTest(Framework.DataAccessGateway.Core.IDBHandler dbHandler)
		{
			Data = new Data_Repository(dbHandler);;
			SubTable = new SubTable_Repository(dbHandler);;
			sysdiagrams = new sysdiagrams_Repository(dbHandler);;
		}
		
		public DAGUnitTest(string connectionString)
		{
			IDBHandler dbHandler = new DBHandler(connectionString, DBHandlerType.DbHandlerMSSQL);
			Data = new Data_Repository(dbHandler);;
			SubTable = new SubTable_Repository(dbHandler);;
			sysdiagrams = new sysdiagrams_Repository(dbHandler);;
		}
	}
}

