//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccessGateway.Automation.DAGUnitTest
{
	using System;
	using System.Data;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using Framework.DataAccessGateway.Core;
	
	
	public class Data_Key
	{
		
		public System.Guid Id { get; set; }
		
		public long BigInt { get; set; }
	}
	
	public class Data
	{
		
		public System.Guid Id { get; set; }
		
		public long BigInt { get; set; }
		
		public byte[] Binary { get; set; }
		
		public System.Nullable<bool> Bit { get; set; }
		
		public string Char { get; set; }
		
		public System.Nullable<System.DateTime> Date { get; set; }
		
		public System.Nullable<System.DateTime> DateTime { get; set; }
		
		public System.Nullable<System.DateTime> DateTime2 { get; set; }
		
		public System.Nullable<System.DateTime> SmallDateTime { get; set; }
		
		public System.Nullable<System.DateTimeOffset> DateTimeOffset { get; set; }
		
		public System.Nullable<decimal> Decimal { get; set; }
		
		public System.Nullable<double> Float { get; set; }
		
		public byte[] Image { get; set; }
		
		public System.Nullable<int> Int { get; set; }
		
		public System.Nullable<decimal> Money { get; set; }
		
		public string NChar { get; set; }
		
		public string NText { get; set; }
		
		public string NVarChar { get; set; }
		
		public System.Nullable<float> Real { get; set; }
		
		public System.Nullable<decimal> SmallMoney { get; set; }
		
		public string Text { get; set; }
		
		public byte[] VarBinary { get; set; }
		
		public string VarChar { get; set; }
	}
	
	public class Data_Ext
	{
		
		public System.Guid _Id { get; set; }
		
		public long _BigInt { get; set; }
		
		public System.Guid Id { get; set; }
		
		public long BigInt { get; set; }
		
		public byte[] Binary { get; set; }
		
		public System.Nullable<bool> Bit { get; set; }
		
		public string Char { get; set; }
		
		public System.Nullable<System.DateTime> Date { get; set; }
		
		public System.Nullable<System.DateTime> DateTime { get; set; }
		
		public System.Nullable<System.DateTime> DateTime2 { get; set; }
		
		public System.Nullable<System.DateTime> SmallDateTime { get; set; }
		
		public System.Nullable<System.DateTimeOffset> DateTimeOffset { get; set; }
		
		public System.Nullable<decimal> Decimal { get; set; }
		
		public System.Nullable<double> Float { get; set; }
		
		public byte[] Image { get; set; }
		
		public System.Nullable<int> Int { get; set; }
		
		public System.Nullable<decimal> Money { get; set; }
		
		public string NChar { get; set; }
		
		public string NText { get; set; }
		
		public string NVarChar { get; set; }
		
		public System.Nullable<float> Real { get; set; }
		
		public System.Nullable<decimal> SmallMoney { get; set; }
		
		public string Text { get; set; }
		
		public byte[] VarBinary { get; set; }
		
		public string VarChar { get; set; }
	}
}

