//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccessGateway.Automation.DAGUnitTest
{
	using System;
	using System.Data;
	using System.Collections.Generic;
	using Framework.DataAccessGateway.Core;
	
	
	public class Data_Repository
	{
		
		public Framework.DataAccessGateway.Core.IDBHandler DBHandler { get; set; }
		
		public Data_Repository()
		{
		}
		
		public virtual void _datainsert(Data Data)
		{
			return null;
		}
		
		public virtual void (Data_Ext Data)
		{
			return null;
		}
		
		public virtual void _datadeletebykey(Data_Key Data)
		{
			return null;
		}
		
		public virtual Data _datagetbykey(Data_Key Data)
		{
			return null;
		}
		
		public virtual List<Data> _datagetall()
		{
			return null;
		}
		
		public virtual void _data_udtt_insert(List<Data> Data)
		{
			return null;
		}
		
		public virtual void (List<Data> Data)
		{
			return null;
		}
	}
}

