//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccessGateway.Automation.DAGUnitTest
{
	using System;
	using System.Data;
	using System.Collections.Generic;
	using Framework.DataAccessGateway.Core;
	
	
	public partial class SubTable_Repository
	{
		
		public Framework.DataAccessGateway.Core.IDBHandler DBHandler { get; set; }
		
		public SubTable_Repository(Framework.DataAccessGateway.Core.IDBHandler dbHandler)
		{
			DBHandler = dbHandler;
		}
		
		public virtual void _subtableinsert(SubTable SubTable)
		{
		}
		
		public virtual void (SubTable_Ext SubTable)
		{
		}
		
		public virtual void _subtabledeletebykey(SubTable_Key SubTable)
		{
		}
		
		public virtual SubTable _subtablegetbykey(SubTable_Key SubTable)
		{
			return null;
		}
		
		public virtual List<SubTable> _subtablegetall()
		{
			return null;
		}
		
		public virtual void _subtabledeletebybigint(long BigInt)
		{
		}
		
		public virtual List<SubTable> _subtablegetbybigint(long BigInt)
		{
			return null;
		}
		
		public virtual void _subtabledeletebydata_id(System.Guid Data_Id)
		{
		}
		
		public virtual List<SubTable> _subtablegetbydata_id(System.Guid Data_Id)
		{
			return null;
		}
		
		public virtual void _subtabledeleteby_bigint_data_id(SubTable_Ext SubTable)
		{
		}
		
		public virtual List<SubTable> _subtablegetby_bigint_data_id(SubTable_Ext SubTable)
		{
			return null;
		}
		
		public virtual void _subtable_udtt_insert(List<SubTable> SubTable)
		{
		}
		
		public virtual void (List<SubTable> SubTable)
		{
		}
	}
}

