//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccessGateway.Automation.DAGUnitTest
{
	using System;
	using System.Data;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using Framework.DataAccessGateway.Core;
	
	
	public class SubTable_Key
	{
		
		public int Id { get; set; }
	}
	
	public class SubTable
	{
		
		public int Id { get; set; }
		
		public long BigInt { get; set; }
		
		public System.Guid Data_Id { get; set; }
	}
	
	public class SubTable_Ext
	{
		
		public int _Id { get; set; }
		
		public int Id { get; set; }
		
		public long BigInt { get; set; }
		
		public System.Guid Data_Id { get; set; }
	}
}

