//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccessGateway.Automation.DAGUnitTest
{
	using System;
	using System.Data;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using Framework.DataAccessGateway.Core;
	
	
	public class sysdiagrams_Key
	{
		
		public int diagram_id { get; set; }
	}
	
	public class sysdiagrams
	{
		
		public string name { get; set; }
		
		public int principal_id { get; set; }
		
		public int diagram_id { get; set; }
		
		public System.Nullable<int> version { get; set; }
		
		public byte[] definition { get; set; }
	}
	
	public class sysdiagrams_Ext
	{
		
		public int _diagram_id { get; set; }
		
		public string name { get; set; }
		
		public int principal_id { get; set; }
		
		public int diagram_id { get; set; }
		
		public System.Nullable<int> version { get; set; }
		
		public byte[] definition { get; set; }
	}
}

