//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccessGateway.Automation.DAGUnitTest
{
	using System;
	using System.Data;
	using System.Collections.Generic;
	using Framework.DataAccessGateway.Core;
	using Framework.AssetLibrary.Types;
	
	
	public partial class sysdiagrams_Repository
	{
		
		public Framework.DataAccessGateway.Core.IDBHandler DBHandler { get; set; }
		
		public sysdiagrams_Repository(Framework.DataAccessGateway.Core.IDBHandler dbHandler)
		{
			DBHandler = dbHandler;
		}
		
		public virtual void sysdiagramsInsert(sysdiagrams sysdiagrams)
		{
DBHandler.ExecuteNonQuery("_sysdiagramsInsert", sysdiagrams, CommandType.StoredProcedure);
		}
		
		public virtual void sysdiagramsUpdate(sysdiagrams_Ext sysdiagrams)
		{
DBHandler.ExecuteNonQuery("_sysdiagramsUpdate", sysdiagrams, CommandType.StoredProcedure);
		}
		
		public virtual void sysdiagramsDeleteByKey(sysdiagrams_Key sysdiagrams)
		{
DBHandler.ExecuteNonQuery("_sysdiagramsDeleteByKey", sysdiagrams, CommandType.StoredProcedure);
		}
		
		public virtual sysdiagrams sysdiagramsGetByKey(sysdiagrams_Key sysdiagrams)
		{
			return;
		}
		
		public virtual List<sysdiagrams> sysdiagramsGetAll()
		{
			return;
		}
		
		public virtual void sysdiagramsUDTTInsert(List<sysdiagrams> sysdiagrams)
		{
DBHandler.ExecuteNonQuery("_sysdiagrams_UDTT_Insert", sysdiagrams.ToDataTable(), CommandType.StoredProcedure);
		}
		
		public virtual void sysdiagramsUDTTUpdate(List<sysdiagrams> sysdiagrams)
		{
DBHandler.ExecuteNonQuery("_sysdiagrams_UDTT_Update", sysdiagrams.ToDataTable(), CommandType.StoredProcedure);
		}
	}
}

